fix(rome_formatter): `write` dropped while still borrowed
This fixes an issue where using `write!` with a borrowed value didn't compile at the end of a block

```
error[E0597]: `right` does not live long enough
   --> crates/rome_js_formatter/src/utils/binary_like_expression.rs:529:70
    |
529 |                 write!(f, [format_sub_expression(parent.operator()?, &right)])
    |                            ------------------------------------------^^^^^^-
    |                            |                                         |
    |                            |                                         borrowed value does not live long enough
    |                            a temporary with access to the borrow is created here ...
530 |             }
    |             -
    |             |
    |             `right` dropped here while still borrowed
    |             ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `impl rome_formatter::Format<context::JsFormatContext>`
    |
    = note: the temporary is part of an expression at the end of a block;
            consider forcing this temporary to be dropped sooner, before the block's local variables are dropped
help: for example, you could save the expression's value in a new local variable `x` and then make `x` be the expression at the end of the block
   --> |/home/micha/git/rome/crates/rome_formatter/src/macros.rs:70:9
    |
70  |         let x = $dst.write_fmt($crate::format_args!($($arg),+)); x
```

This PR implements the recommended fix as part of the macro, similar to `std::write!`

## Test

Having the `write!` call being the last expression in the block compiles successfully